version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      #- restore_cache:
      #    name: Restore cached dependencies
      #    key: pyness-{{ checksum "requirements.dev.txt" }}

      - run:
          name: Install virtual environment
          command: |
            curl https://pyenv.run | bash
            export PATH="$HOME/.pyenv/bin:$PATH"
            echo "export PATH=$HOME/.pyenv/bin:$PATH" >> $BASH_ENV
            echo "export PYENV_ROOT=$HOME/.pyenv" >> $BASH_ENV
            # git clone https://github.com/pyenv/pyenv-virtualenv.git $HOME/.pyenv/plugins/pyenv-virtualenv
            # exec $SHELL

      # - run:
      #     name: Configure virtual environment
      #     command: |

      - run:
          name: Install dependencies
          command: |
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv virtualenv ness
            pyenv activate ness
            pip install -r requirements.dev.txt

      - run:
          name: Run tests
          command: |
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv activate ness
            PYTHONPATH=. pytest tests -v

      - run:
          name: Type checks
          command: |
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv activate ness
            mypy --show-error-codes --ignore-missing-imports --no-strict-optional pyness/log.py
            mypy --show-error-codes --ignore-missing-imports --no-strict-optional pyness/graph.py
            mypy --show-error-codes --ignore-missing-imports --no-strict-optional pyness/ness.py
            mypy --show-error-codes --ignore-missing-imports --no-strict-optional pyness/parse.py
            mypy --show-error-codes --ignore-missing-imports --no-strict-optional pyness/types.py

      - run:
          name: Style checks
          command: |
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            pyenv activate ness
            flake8 pyness

      - save_cache:
          name: Cache dependencies
          key: pyness-{{ checksum "requirements.dev.txt" }}
          paths:
            - $HOME/.pyenv
