version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:
          name: Restore cached dependencies
          key: pyness-v1.0.0-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: sudo pip install -r requirements.txt

      - run:
          name: Run tests
          command: PYTHONPATH=. pytest tests -v

      - run:
          name: Type checks
          command: mypy --show-error-codes --ignore-missing-imports --no-strict-optional pyness

      - run:
          name: Style checks
          command: flake8 pyness

      - save_cache:
          name: Cache dependencies
          key: pyness-v1.0.0-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.7/site-packages
            - /usr/local/bin
